// Generated by CoffeeScript 1.4.0
(function() {
  var stubFn;

  stubFn = function(returnValue) {
    var fn;
    fn = function() {
      fn.called = true;
      fn.args = Array.prototype.slice.call(arguments);
      return returnValue;
    };
    fn.called = false;
    return fn;
  };

}).call(this);
